### ISSUE TITLE
ClassNotFoundException when starting the app

### ISSUE THREAD

**Issue by rz-robsn** [richardradics/RxAndroidBootstrap#1]
Hi @richardradics,

I was checking out your project in order to learn RxJava. But when I tried to run it, I systematically get an exception as soon as I start the app :

```
    --------- beginning of /dev/log/main
07-16 22:11:47.712    3806-3806/com.richardradics.cleanrx D/AndroidRuntime﹕ Shutting down VM
07-16 22:11:47.712    3806-3806/com.richardradics.cleanrx W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xa4b8c648)
    --------- beginning of /dev/log/system
07-16 22:11:47.716    3806-3806/com.richardradics.cleanrx E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to instantiate application com.richardradics.cleanrx.app.CleanApplication: java.lang.ClassNotFoundException: Didn't find class "com.richardradics.cleanrx.app.CleanApplication" on path: DexPathList[[zip file "/data/app/com.richardradics.cleanrx-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.richardradics.cleanrx-1, /system/lib]]
            at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4417)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.richardradics.cleanrx.app.CleanApplication" on path: DexPathList[[zip file "/data/app/com.richardradics.cleanrx-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.richardradics.cleanrx-1, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at android.app.Instrumentation.newApplication(Instrumentation.java:975)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4417)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
07-16 22:11:47.720      361-372/system_process W/ActivityManager﹕ Force finishing activity com.richardradics.cleanrx/.ui.activity.MainActivity
```

The commit at which I reproduced the crash is the latest one, which at the moment of writing is #87f5d51993da0ca4424804cded057ba4f02e9403.

My current version of android studio is 1.3 RC 1. I tried to run the application on both the genymotion emulator and a physical phone, both of which were on lollipop. 

If you need any more details about my setup, don't hesitate to ask me !

**Comment by radityagumay** [comment]
Hi,

I Also Facing same issue.

Thanks for you great code!

**Comment by richardradics** [comment]
Hi guys @rz-robsn @radityagumay 

Thanks for your feedback.
I'm going to check it now.

**Comment by radityagumay** [comment]
Hi @richardradics 

Thanks for reply

**Comment by radityagumay** [comment]
Hi @richardradics have you fix the error? thanks
